baseURL = 'https://stevenhay.com/'
languageCode = 'en-us'
title = 'Steven Hay'
pluralizelisttitles = false
enableEmoji = true

[params]
description = "Steven Hay - Engineer and researcher transitioning to computational neuroscience. Writings on neural computation, machine learning, and systems engineering."
author = "Steven Hay"

[outputs]
home = ['html', 'rss']

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 1

[[menus.main]]
name = 'CV'
url = '/docs/cv/cv-steve-hay.pdf'
params = { target = "_blank" }
weight = 111

[[menus.main]]
name = 'Portfolio'
pageRef = '/portfolio'
weight = 210

[[menus.main]]
name = 'Writing'
pageRef = '/writing'
weight = 510

[[menus.main]]
name = 'Contact'
pageRef = '/contact'
weight = 1000
